MusicManager\ManageBundle\Entity\Band:
    type: entity
    table: band
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
