MusicManager\ManageBundle\Entity\Song:
    type: entity
    table: song
    indexes:
        IDX_33EDEEA11137ABCF:
            columns:
                - album_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
        length:
            type: string
            nullable: true
            length: 12
            fixed: false
    manyToOne:
        album:
            targetEntity: Album
            cascade: {  }
            mappedBy: null
            inversedBy: songs
            joinColumns:
                album_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
